# Generated by Django 5.2.6 on 2025-11-05 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('tiu_id', models.AutoField(primary_key=True, serialize=False)),
                ('tiu_nombre', models.TextField()),
                ('tiu_fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tiu_fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('tiu_vigencia', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='tiu_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='users.tipousuario'),
        ),
    ]
