# Generated by Django 5.2.6 on 2025-09-27 20:57

import django.db.models.deletion
import solicitudes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoSolicitud',
            fields=[
                ('est_id', models.AutoField(primary_key=True, serialize=False)),
                ('est_nombre', models.CharField(max_length=80)),
                ('est_vigencia', models.BooleanField(default=True)),
                ('est_fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BitacoraSolicitud',
            fields=[
                ('bsca_id', models.AutoField(primary_key=True, serialize=False)),
                ('bsca_observacion', models.TextField()),
                ('bsca_fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('bsca_fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('bsca_usuario_actualizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas_bitacora', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-bsca_fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudAyuda',
            fields=[
                ('sca_id', models.AutoField(primary_key=True, serialize=False)),
                ('sca_titulo', models.CharField(max_length=200)),
                ('sca_descripcion', models.TextField()),
                ('sca_fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('sca_fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('est_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='solicitudes.estadosolicitud')),
                ('sca_usuario_actualizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_creadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoSolicitud',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_archivo', models.FileField(upload_to=solicitudes.models.ruta_archivos_solicitud)),
                ('doc_fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('doc_fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('bitacora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='solicitudes.bitacorasolicitud')),
                ('doc_usuario_actualizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='solicitudes.solicitudayuda')),
            ],
        ),
        migrations.AddField(
            model_name='bitacorasolicitud',
            name='sca_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacora', to='solicitudes.solicitudayuda'),
        ),
    ]
